### ISSUE TITLE
Program crashing when switching to "plan to watch" or "on hold"

### ISSUE THREAD

**Issue by sotojuan** [IllDepence/anihilist#1]
Hi, when I press 3 or 4 to go to the associated lists, the program crashes and spits this out:

```
Traceback (most recent call last):
  File "anihilist.py", line 502, in <module>
    curses.wrapper(main)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "anihilist.py", line 466, in main
    anime_list.setListKey('plan_to_watch')
  File "anihilist.py", line 168, in setListKey
    self._updateEntries()
  File "anihilist.py", line 157, in _updateEntries
    list_processed.append(Anime(al_data, self.xdcc_info, self))
  File "anihilist.py", line 49, in __init__
    if ep_total > 0:
TypeError: unorderable types: NoneType() > int()
```

Otherwise it works. Really awesome tool!

**Comment by IllDepence** [comment]
should be fixed now
please let me know if the problem is resolved for you, too

**Comment by sotojuan** [comment]
Yup, everything working now. Thanks!
